"use client";

import React, { useEffect, useRef, useMemo } from "react";
import worldBordersData from "./worldBorders.json";
import landDotsData from "./landDots.json";

interface CountryNode {
  name: string;
  country: string;
  code: string;
  lat: number;
  lng: number;
  isTarget?: boolean;
}

interface AttackArc {
  id: string;
  source: CountryNode;
  target: CountryNode;
  progress: number;
  speed: number;
  color: string;
  altitude: number;
}

interface ImpactPulse {
  x: number;
  y: number;
  radius: number;
  maxRadius: number;
  color: string;
  opacity: number;
}

// Target Hub is Nepal (NP) as requested in the reference image
const TARGET_NEPAL: CountryNode = {
  name: "Kathmandu",
  country: "Nepal",
  code: "NP",
  lat: 28.39,
  lng: 84.12,
  isTarget: true,
};

// Attacking and prominent world countries (same as reference image: US, DE, CN, TR, etc.)
const ATTACKING_COUNTRIES: CountryNode[] = [
  { name: "Washington", country: "United States", code: "US", lat: 38.9, lng: -77.0 },
  { name: "Frankfurt", country: "Germany", code: "DE", lat: 50.1, lng: 8.68 },
  { name: "Beijing", country: "China", code: "CN", lat: 39.9, lng: 116.4 },
  { name: "Istanbul", country: "Turkey", code: "TR", lat: 41.0, lng: 28.98 },
  { name: "London", country: "United Kingdom", code: "UK", lat: 51.5, lng: -0.12 },
  { name: "Paris", country: "France", code: "FR", lat: 48.85, lng: 2.35 },
  { name: "Moscow", country: "Russia", code: "RU", lat: 55.75, lng: 37.6 },
  { name: "Tokyo", country: "Japan", code: "JP", lat: 35.68, lng: 139.75 },
  { name: "Sydney", country: "Australia", code: "AU", lat: -33.87, lng: 151.2 },
  { name: "Brasilia", country: "Brazil", code: "BR", lat: -15.8, lng: -47.9 },
  { name: "Buenos Aires", country: "Argentina", code: "AR", lat: -34.6, lng: -58.4 },
  { name: "Delhi", country: "India", code: "IN", lat: 28.6, lng: 77.2 },
  { name: "Bangkok", country: "Thailand", code: "TH", lat: 13.75, lng: 100.5 },
  { name: "Johannesburg", country: "South Africa", code: "ZA", lat: -26.2, lng: 28.0 },
];

// REAL country/coastline borders — sourced from Natural Earth (110m admin-0 countries),
// simplified to ~7,000 points across 270 rings (every landmass + larger islands).
// Coordinates are stored as [lat, lng] rings, matching the projection math below.
const WORLD_BORDERS: [number, number][][] = worldBordersData as [number, number][][];

// REAL land-dot matrix — generated by testing a 2°x2° lat/lng grid against the
// actual merged country geometry (point-in-polygon), so dots only ever land on
// real coastlines instead of hand-drawn rectangular blocks.
const REAL_LAND_DOTS: { lat: number; lng: number }[] = (
  landDotsData as [number, number][]
).map(([lat, lng]) => ({ lat, lng }));

export default function CyberThreatGlobe() {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);

  // 3D rotation angles: initial view centered on Asia / Nepal / Europe
  const rotationRef = useRef({ yaw: -1.45, pitch: 0.22 });
  const isDraggingRef = useRef(false);
  const lastMousePosRef = useRef({ x: 0, y: 0 });

  const activeArcsRef = useRef<AttackArc[]>([]);
  const impactPulsesRef = useRef<ImpactPulse[]>([]);
  const lastSpawnTimeRef = useRef(0);

  // worldDots now comes straight from real geometry — no synthetic block generator needed
  const worldDots = useMemo(() => REAL_LAND_DOTS, []);

  // Canvas render & animation loop
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let animationFrameId: number;

    const resize = () => {
      if (!canvas || !containerRef.current) return;
      const rect = containerRef.current.getBoundingClientRect();
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.floor(rect.width * dpr);
      canvas.height = Math.floor(rect.height * dpr);
    };

    resize();
    window.addEventListener("resize", resize);

    // MATHEMATICALLY ACCURATE SPHERICAL PROJECTION (NOT REVERTED!)
    // East Longitude (+lng) maps to Right (+x)
    // West Longitude (-lng) maps to Left (-x)
    // North Latitude (+lat) maps to Up (+y)
    // South Latitude (-lat) maps to Down (-y)
    const latLngTo3D = (lat: number, lng: number, radius: number) => {
      const phi = (lat * Math.PI) / 180;
      const lambda = (lng * Math.PI) / 180;
      return {
        x: radius * Math.cos(phi) * Math.sin(lambda),
        y: radius * Math.sin(phi),
        z: radius * Math.cos(phi) * Math.cos(lambda),
      };
    };

    // Rotate 3D vector by yaw (spin) and pitch (tilt)
    const rotate3D = (x: number, y: number, z: number, yaw: number, pitch: number) => {
      // Rotate around Y axis (spin)
      const cosY = Math.cos(yaw);
      const sinY = Math.sin(yaw);
      const x1 = x * cosY + z * sinY;
      const z1 = -x * sinY + z * cosY;

      // Rotate around X axis (pitch)
      const cosP = Math.cos(pitch);
      const sinP = Math.sin(pitch);
      const y2 = y * cosP - z1 * sinP;
      const z2 = y * sinP + z1 * cosP;

      return { x: x1, y: y2, z: z2 };
    };

    // Spawn live attack targeting Nepal from one of the active countries
    const spawnAttack = (timestamp: number) => {
      if (timestamp - lastSpawnTimeRef.current > 1400 && activeArcsRef.current.length < 6) {
        lastSpawnTimeRef.current = timestamp;

        // Choose random attacker (e.g. US, DE, CN, TR, UK, etc.)
        const source = ATTACKING_COUNTRIES[Math.floor(Math.random() * ATTACKING_COUNTRIES.length)];
        const target = TARGET_NEPAL;

        const colors = ["#f87171", "#fb7185", "#f43f5e", "#ef4444"];
        const arcColor = colors[Math.floor(Math.random() * colors.length)];

        const newArc: AttackArc = {
          id: Math.random().toString(36).substring(7),
          source,
          target,
          progress: 0,
          speed: 0.009 + Math.random() * 0.005,
          color: arcColor,
          altitude: 0.25 + Math.random() * 0.15,
        };

        activeArcsRef.current.push(newArc);
      }
    };

    const render = (time: number) => {
      if (!canvas || !containerRef.current) return;
      const width = containerRef.current.clientWidth;
      const height = containerRef.current.clientHeight;
      const globeRadius = Math.min(width, height) * 0.38;
      const centerX = width / 2;
      const centerY = height / 2;

      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      ctx.clearRect(0, 0, width, height);

      // Smooth auto rotation (West to East)
      if (!isDraggingRef.current) {
        rotationRef.current.yaw += 0.0028;
      }

      const { yaw, pitch } = rotationRef.current;

      // 1. Atmosphere Glow Halo
      const haloGradient = ctx.createRadialGradient(
        centerX,
        centerY,
        globeRadius * 0.8,
        centerX,
        centerY,
        globeRadius * 1.3
      );
      haloGradient.addColorStop(0, "rgba(61, 115, 189, 0.22)");
      haloGradient.addColorStop(0.5, "rgba(61, 115, 189, 0.08)");
      haloGradient.addColorStop(1, "transparent");

      ctx.fillStyle = haloGradient;
      ctx.beginPath();
      ctx.arc(centerX, centerY, globeRadius * 1.3, 0, Math.PI * 2);
      ctx.fill();

      // 2. Base Dark Globe Sphere
      const sphereGradient = ctx.createRadialGradient(
        centerX - globeRadius * 0.35,
        centerY - globeRadius * 0.35,
        globeRadius * 0.1,
        centerX,
        centerY,
        globeRadius
      );
      sphereGradient.addColorStop(0, "#1d3c68");
      sphereGradient.addColorStop(0.65, "#0b182d");
      sphereGradient.addColorStop(1, "#050d1a");

      ctx.save();
      ctx.beginPath();
      ctx.arc(centerX, centerY, globeRadius, 0, Math.PI * 2);
      ctx.fillStyle = sphereGradient;
      ctx.fill();

      // Globe Rim Ring
      ctx.strokeStyle = "rgba(90, 143, 217, 0.5)";
      ctx.lineWidth = 1.5;
      ctx.stroke();
      ctx.clip(); // Clip inside globe

      // 3. Latitude and Longitude Grid
      ctx.strokeStyle = "rgba(61, 115, 189, 0.16)";
      ctx.lineWidth = 0.8;

      // Latitude Rings
      for (let lat = -60; lat <= 60; lat += 30) {
        ctx.beginPath();
        let first = true;
        for (let lng = -180; lng <= 180; lng += 6) {
          const pt3D = latLngTo3D(lat, lng, globeRadius);
          const rotated = rotate3D(pt3D.x, pt3D.y, pt3D.z, yaw, pitch);
          if (rotated.z > -globeRadius * 0.2) {
            const screenX = centerX + rotated.x;
            const screenY = centerY - rotated.y; // Invert Y for canvas
            if (first) {
              ctx.moveTo(screenX, screenY);
              first = false;
            } else {
              ctx.lineTo(screenX, screenY);
            }
          } else {
            first = true;
          }
        }
        ctx.stroke();
      }

      // Longitude Lines
      for (let lng = -180; lng < 180; lng += 45) {
        ctx.beginPath();
        let first = true;
        for (let lat = -80; lat <= 80; lat += 6) {
          const pt3D = latLngTo3D(lat, lng, globeRadius);
          const rotated = rotate3D(pt3D.x, pt3D.y, pt3D.z, yaw, pitch);
          if (rotated.z > -globeRadius * 0.2) {
            const screenX = centerX + rotated.x;
            const screenY = centerY - rotated.y;
            if (first) {
              ctx.moveTo(screenX, screenY);
              first = false;
            } else {
              ctx.lineTo(screenX, screenY);
            }
          } else {
            first = true;
          }
        }
        ctx.stroke();
      }

      // 4. Draw Real World Country / Coastline Outlines (Natural Earth 110m data)
      ctx.strokeStyle = "rgba(90, 155, 235, 0.65)";
      ctx.lineWidth = 1.1;
      ctx.fillStyle = "rgba(19, 38, 68, 0.55)";

      WORLD_BORDERS.forEach((polygon) => {
        ctx.beginPath();
        let started = false;
        polygon.forEach(([lat, lng]) => {
          const pt = latLngTo3D(lat, lng, globeRadius);
          const rot = rotate3D(pt.x, pt.y, pt.z, yaw, pitch);
          if (rot.z > -globeRadius * 0.1) {
            const sx = centerX + rot.x;
            const sy = centerY - rot.y;
            if (!started) {
              ctx.moveTo(sx, sy);
              started = true;
            } else {
              ctx.lineTo(sx, sy);
            }
          } else {
            started = false;
          }
        });
        ctx.stroke();
      });

      // 5. Draw Land Dot Matrix (real point-in-polygon coverage, not synthetic blocks)
      worldDots.forEach((dot) => {
        const pt = latLngTo3D(dot.lat, dot.lng, globeRadius);
        const rot = rotate3D(pt.x, pt.y, pt.z, yaw, pitch);
        if (rot.z > 0) {
          const depthAlpha = (rot.z / globeRadius) * 0.8 + 0.18;
          ctx.fillStyle = `rgba(145, 195, 255, ${depthAlpha})`;
          ctx.beginPath();
          ctx.arc(centerX + rot.x, centerY - rot.y, 1.3, 0, Math.PI * 2);
          ctx.fill();
        }
      });

      // 6. Draw Focal Target Beacon: NEPAL (NP)
      const npPt = latLngTo3D(TARGET_NEPAL.lat, TARGET_NEPAL.lng, globeRadius);
      const npRot = rotate3D(npPt.x, npPt.y, npPt.z, yaw, pitch);

      if (npRot.z > 0) {
        const sx = centerX + npRot.x;
        const sy = centerY - npRot.y;
        const depthAlpha = Math.min(1, Math.max(0.3, npRot.z / globeRadius));

        // Expanding pulsating rings on Nepal
        const pulseSize = (time % 2000) / 2000;
        ctx.strokeStyle = `rgba(96, 165, 250, ${(1 - pulseSize) * depthAlpha})`;
        ctx.lineWidth = 1.5;
        ctx.beginPath();
        ctx.arc(sx, sy, 8 + pulseSize * 18, 0, Math.PI * 2);
        ctx.stroke();

        // Blue target halo
        ctx.fillStyle = `rgba(59, 130, 246, ${0.45 * depthAlpha})`;
        ctx.beginPath();
        ctx.arc(sx, sy, 9, 0, Math.PI * 2);
        ctx.fill();

        // Blue target core
        ctx.fillStyle = "#3b82f6";
        ctx.beginPath();
        ctx.arc(sx, sy, 5, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = "#ffffff";
        ctx.beginPath();
        ctx.arc(sx, sy, 2.5, 0, Math.PI * 2);
        ctx.fill();

        // Nepal Country Label
        ctx.fillStyle = `rgba(255, 255, 255, ${depthAlpha})`;
        ctx.font = "bold 10px -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
        ctx.shadowColor = "rgba(0,0,0,0.9)";
        ctx.shadowBlur = 4;
        ctx.fillText("Nepal (NP)", sx + 8, sy + 3);
        ctx.shadowBlur = 0;
      }

      // 7. Draw Attacking Country Pins & Labels
      ATTACKING_COUNTRIES.forEach((c) => {
        const pt = latLngTo3D(c.lat, c.lng, globeRadius);
        const rot = rotate3D(pt.x, pt.y, pt.z, yaw, pitch);

        if (rot.z > 0) {
          const sx = centerX + rot.x;
          const sy = centerY - rot.y;
          const depthAlpha = Math.min(1, Math.max(0.2, rot.z / globeRadius));

          // Check if this country is currently launching an attack
          const isAttacking = activeArcsRef.current.some((a) => a.source.code === c.code);

          if (isAttacking) {
            // Glowing Red/Amber Pin
            ctx.fillStyle = `rgba(239, 68, 68, ${0.45 * depthAlpha})`;
            ctx.beginPath();
            ctx.arc(sx, sy, 7, 0, Math.PI * 2);
            ctx.fill();

            ctx.fillStyle = `rgba(239, 68, 68, ${0.95 * depthAlpha})`;
            ctx.beginPath();
            ctx.arc(sx, sy, 3.5, 0, Math.PI * 2);
            ctx.fill();

            ctx.fillStyle = "#ffffff";
            ctx.beginPath();
            ctx.arc(sx, sy, 1.8, 0, Math.PI * 2);
            ctx.fill();

            // Noticeable Country Name
            if (rot.z > globeRadius * 0.25) {
              ctx.fillStyle = `rgba(255, 255, 255, ${depthAlpha * 0.95})`;
              ctx.font = "bold 9px -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
              ctx.shadowColor = "rgba(0,0,0,0.85)";
              ctx.shadowBlur = 4;
              ctx.fillText(c.country, sx + 7, sy + 3);
              ctx.shadowBlur = 0;
            }
          } else {
            // Subtle node dot
            ctx.fillStyle = `rgba(248, 113, 113, ${0.35 * depthAlpha})`;
            ctx.beginPath();
            ctx.arc(sx, sy, 4, 0, Math.PI * 2);
            ctx.fill();

            ctx.fillStyle = `rgba(255, 255, 255, ${0.85 * depthAlpha})`;
            ctx.beginPath();
            ctx.arc(sx, sy, 2, 0, Math.PI * 2);
            ctx.fill();

            if (rot.z > globeRadius * 0.5) {
              ctx.fillStyle = `rgba(200, 220, 250, ${depthAlpha * 0.75})`;
              ctx.font = "8px ui-monospace, SFMono-Regular, monospace";
              ctx.fillText(c.code, sx + 5, sy - 3);
            }
          }
        }
      });

      ctx.restore(); // Release clipping for 3D attack arcs

      // 8. Spawn and Render Attack Arcs converging into Nepal
      spawnAttack(time);

      const remainingArcs: AttackArc[] = [];

      activeArcsRef.current.forEach((arc) => {
        arc.progress += arc.speed;

        if (arc.progress < 1) {
          remainingArcs.push(arc);

          const p1 = latLngTo3D(arc.source.lat, arc.source.lng, globeRadius);
          const p2 = latLngTo3D(arc.target.lat, arc.target.lng, globeRadius);

          const currentPoint = (t: number) => {
            const rawX = p1.x * (1 - t) + p2.x * t;
            const rawY = p1.y * (1 - t) + p2.y * t;
            const rawZ = p1.z * (1 - t) + p2.z * t;
            const len = Math.sqrt(rawX * rawX + rawY * rawY + rawZ * rawZ);

            const elevation = Math.sin(t * Math.PI) * (globeRadius * arc.altitude);
            const r = globeRadius + elevation;

            const x = (rawX / len) * r;
            const y = (rawY / len) * r;
            const z = (rawZ / len) * r;

            return rotate3D(x, y, z, yaw, pitch);
          };

          // Trajectory Tail
          const segments = 24;
          const currentSegIndex = Math.floor(arc.progress * segments);

          ctx.beginPath();
          let started = false;
          const trailLength = 9;
          const startSeg = Math.max(0, currentSegIndex - trailLength);

          for (let s = startSeg; s <= currentSegIndex; s++) {
            const t = s / segments;
            const rot = currentPoint(t);

            if (rot.z > -globeRadius * 0.15) {
              const sx = centerX + rot.x;
              const sy = centerY - rot.y; // Invert Y
              if (!started) {
                ctx.moveTo(sx, sy);
                started = true;
              } else {
                ctx.lineTo(sx, sy);
              }
            }
          }

          if (started) {
            ctx.strokeStyle = arc.color;
            ctx.lineWidth = 2.4;
            ctx.shadowColor = arc.color;
            ctx.shadowBlur = 10;
            ctx.stroke();
            ctx.shadowBlur = 0;
          }

          // Glowing Missile Projectile Head
          const headRot = currentPoint(arc.progress);
          if (headRot.z > -globeRadius * 0.1) {
            const headX = centerX + headRot.x;
            const headY = centerY - headRot.y;

            ctx.fillStyle = "#ffffff";
            ctx.beginPath();
            ctx.arc(headX, headY, 3.2, 0, Math.PI * 2);
            ctx.fill();

            ctx.fillStyle = arc.color;
            ctx.beginPath();
            ctx.arc(headX, headY, 5.5, 0, Math.PI * 2);
            ctx.fill();

            // 3D Country tag above missile
            if (arc.progress > 0.2 && arc.progress < 0.8 && headRot.z > 0) {
              ctx.save();
              ctx.font = "bold 9px ui-monospace, monospace";
              const tagText = `${arc.source.code} ➔ NP`;
              const textWidth = ctx.measureText(tagText).width;

              ctx.fillStyle = "rgba(7, 18, 36, 0.88)";
              ctx.strokeStyle = arc.color;
              ctx.lineWidth = 1;
              ctx.beginPath();
              ctx.roundRect(headX - textWidth / 2 - 5, headY - 19, textWidth + 10, 14, 4);
              ctx.fill();
              ctx.stroke();

              ctx.fillStyle = "#ffffff";
              ctx.fillText(tagText, headX - textWidth / 2, headY - 9);
              ctx.restore();
            }
          }
        } else {
          // Impact Ripple on Nepal
          const npRot = rotate3D(npPt.x, npPt.y, npPt.z, yaw, pitch);
          if (npRot.z > 0) {
            impactPulsesRef.current.push({
              x: centerX + npRot.x,
              y: centerY - npRot.y,
              radius: 4,
              maxRadius: 28,
              color: arc.color,
              opacity: 0.95,
            });
          }
        }
      });

      activeArcsRef.current = remainingArcs;

      // 9. Render Expanding Impact Pulses
      const remainingPulses: ImpactPulse[] = [];
      impactPulsesRef.current.forEach((pulse) => {
        pulse.radius += 0.95;
        pulse.opacity -= 0.035;

        if (pulse.opacity > 0 && pulse.radius < pulse.maxRadius) {
          remainingPulses.push(pulse);

          ctx.strokeStyle = pulse.color;
          ctx.lineWidth = 1.6;
          ctx.globalAlpha = pulse.opacity;
          ctx.beginPath();
          ctx.arc(pulse.x, pulse.y, pulse.radius, 0, Math.PI * 2);
          ctx.stroke();
          ctx.globalAlpha = 1;
        }
      });
      impactPulsesRef.current = remainingPulses;

      animationFrameId = requestAnimationFrame(render);
    };

    animationFrameId = requestAnimationFrame(render);

    return () => {
      cancelAnimationFrame(animationFrameId);
      window.removeEventListener("resize", resize);
    };
  }, [worldDots]);

  // Mouse / Touch Interaction for Manual 3D Drag
  const handleMouseDown = (e: React.MouseEvent) => {
    isDraggingRef.current = true;
    lastMousePosRef.current = { x: e.clientX, y: e.clientY };
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!isDraggingRef.current) return;
    const deltaX = e.clientX - lastMousePosRef.current.x;
    const deltaY = e.clientY - lastMousePosRef.current.y;

    rotationRef.current.yaw += deltaX * 0.006;
    rotationRef.current.pitch = Math.max(
      -1.2,
      Math.min(1.2, rotationRef.current.pitch + deltaY * 0.006)
    );

    lastMousePosRef.current = { x: e.clientX, y: e.clientY };
  };

  const handleMouseUp = () => {
    isDraggingRef.current = false;
  };

  const handleTouchStart = (e: React.TouchEvent) => {
    if (e.touches.length === 1) {
      isDraggingRef.current = true;
      lastMousePosRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
    }
  };

  const handleTouchMove = (e: React.TouchEvent) => {
    if (!isDraggingRef.current || e.touches.length !== 1) return;
    const deltaX = e.touches[0].clientX - lastMousePosRef.current.x;
    const deltaY = e.touches[0].clientY - lastMousePosRef.current.y;

    rotationRef.current.yaw += deltaX * 0.007;
    rotationRef.current.pitch = Math.max(
      -1.2,
      Math.min(1.2, rotationRef.current.pitch + deltaY * 0.007)
    );

    lastMousePosRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
  };

  const handleTouchEnd = () => {
    isDraggingRef.current = false;
  };

  return (
    <div className="relative flex flex-col items-center select-none w-full max-w-[480px]">
      {/* 3D Interactive Cyber Threat Globe Canvas */}
      <div
        ref={containerRef}
        className="relative w-full aspect-square cursor-grab active:cursor-grabbing bg-transparent flex items-center justify-center"
        onMouseDown={handleMouseDown}
        onMouseMove={handleMouseMove}
        onMouseUp={handleMouseUp}
        onMouseLeave={handleMouseUp}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        <canvas ref={canvasRef} className="w-full h-full block" />
      </div>

      {/* Live Attacks Bar (Matches the attached reference image) */}
      <div className="mt-2 inline-flex items-center gap-2 sm:gap-3 px-4 py-2 rounded-full bg-slate-900/90 border border-[#3d73bd]/35 shadow-lg backdrop-blur-md text-white text-xs font-mono">
        <span className="text-[11px] sm:text-xs font-bold tracking-wider uppercase text-slate-300">
          LIVE ATTACKS:
        </span>
        <div className="flex items-center gap-2 sm:gap-2.5 flex-wrap">
          <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-red-950/40 border border-red-900/40 text-[11px]">
            <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-ping" />
            <span className="font-semibold text-red-300">US</span>
            <span className="text-slate-400">➔</span>
            <span className="font-semibold text-blue-300">NP</span>
          </div>
          <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-red-950/40 border border-red-900/40 text-[11px]">
            <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-ping" />
            <span className="font-semibold text-red-300">DE</span>
            <span className="text-slate-400">➔</span>
            <span className="font-semibold text-blue-300">NP</span>
          </div>
          <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-red-950/40 border border-red-900/40 text-[11px]">
            <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-ping" />
            <span className="font-semibold text-red-300">CN</span>
            <span className="text-slate-400">➔</span>
            <span className="font-semibold text-blue-300">NP</span>
          </div>
          <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-red-950/40 border border-red-900/40 text-[11px]">
            <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-ping" />
            <span className="font-semibold text-red-300">TR</span>
            <span className="text-slate-400">➔</span>
            <span className="font-semibold text-blue-300">NP</span>
          </div>
        </div>
      </div>
    </div>
  );
}