"use client";

import React, { useMemo } from "react";
import { sanitizeHtml, isHtml } from "@/lib/html-utils";

interface RichTextContentProps {
  content?: string | null;
  className?: string;
  as?: "div" | "span" | "article" | "section";
}

/**
 * RichTextContent Component
 * Safely renders rich HTML generated by the RichTextEditor.
 * Also backwards-compatible with legacy plain text containing "\n" newlines.
 */
export const RichTextContent: React.FC<RichTextContentProps> = ({
  content,
  className = "",
  as: Component = "div",
}) => {
  if (!content || !content.trim()) return null;

  const hasMarkup = useMemo(() => isHtml(content), [content]);

  // If content contains rich HTML markup, sanitize and inject
  const sanitizedHtml = useMemo(() => {
    if (!hasMarkup) return "";
    return sanitizeHtml(content);
  }, [content, hasMarkup]);

  if (hasMarkup) {
    return (
      <Component
        className={`rich-text-content ${className}`.trim()}
        dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
      />
    );
  }

  // Legacy plain text handling: split by newlines into paragraphs
  const paragraphs = content
    .split("\n")
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <Component className={`rich-text-content space-y-3 ${className}`.trim()}>
      {paragraphs.map((para, idx) => (
        <p key={idx}>{para}</p>
      ))}
    </Component>
  );
};

export default RichTextContent;
